name: StaffChat
version: 1.1.1
api:
- 3.0.0
author: Thunder33345
website: "https://github.com/ThunderDoesPlugins/StaffChat"
description: "Private Staff Chat Plugin"
main: Thunder33345\StaffChat\StaffChat

commands:
  staffchat:
    description: ""
    aliases: ['sc']

permissions:
  staffchat:
    default: op
    children:
      staffchat.read:
        default: false
        description: "Read from staff chat"
      staffchat.chat:
        default: false
        description: "Chat into staff chat"
      staffchat.attach:
        default: false
        description: "Attach console into staff chat"
      staffchat.check:
        default: false
        description: "Check other players status"
      staffchat.list:
        default: false
        description: "Show info list of players"
